### ISSUE TITLE
Translate README.md to Word Doc

### ISSUE THREAD

**Issue by HaffCaff** [CSC-256-Group-Project-9/Group-9-Selenium-Lab#10]
## Problem:
Translate README.md to convert to Word Doc for lab instructions

**Comment by Sleek5000** [comment]
Uploaded docx file version of the README.md. Can now be used and updated as we move into the lab. Should have a document writer look it over and see if we like the format and do any needed changes.

**Comment by Nate-is-Great** [comment]
Looked over and updated document for use removed step 4 was seen as unnecessary.

**Comment by StefanESlaczka** [comment]
For automation of the md file to Word. I have tried using Python but I came across an output with a bunch of HTML tags. So we should use Pandoc and it will be easy to convert it because we can just write one line to the termail.

# Pandoc Installation Guide

To perform file conversion using Pandoc, follow these step-by-step instructions:

1. **Download Pandoc:**
   - Visit the Pandoc official website at [https://pandoc.org/installing.html#windows](https://pandoc.org/installing.html#windows).
   - Click on the "Download the latest installer" button.

2. **Choose the Installer:**
   - Download the installer that matches your operating system. For example, if you are using a 64-bit Windows system, you can download a file like `pandoc-3.1.8-windows-x86_64.msi`.

3. **Install Pandoc:**
   - Open the folder where you downloaded the installer.
   - Run the installer program and follow the on-screen instructions to complete the installation.
   - Click "Finish" when the installation process is done.

4. **Verify Installation:**
   - Open your command prompt or terminal.
   - Type the following command to check if Pandoc is correctly installed:
     ```
     pandoc -h
     ```

5. **Convert Markdown to Word:**
   - Navigate to the folder that contains the Markdown file you want to convert to Word.
   - Open your terminal or command prompt.
   - Use the following command to convert the Markdown file (input.md) to a Word document (output.docx):
     ```
     pandoc input.md -o output.docx
     ```

You have now successfully installed Pandoc and converted a Markdown file to a Word document. You can replace "input.md" and "output.docx" with your specific file names as needed.
